[package]
name = "sat_solver"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.25"
rand = "0.9.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false
