[package]
name = "sat_solver_macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.101", features = ["full", "parsing", "visit-mut"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
heck = "0.5.0"
itertools = "0.14.0"
